### ISSUE TITLE
ErrorException: Illegal string offset 'text'

### ISSUE THREAD

**Issue by niclashedam** [lsv/rejseplan-php-api#5]
Today I got the following exception, while getting journey details on an S-train.

```
[2017-02-09 17:03:06] local.ERROR: ErrorException: Illegal string offset 'text' in /Users/niclas/Sites/Transport/vendor/lsv/rejseplan-php-api/src/Services/Response/JourneyResponse.php:95
Stack trace:
#0 /Users/niclas/Sites/Transport/vendor/lsv/rejseplan-php-api/src/Services/Response/JourneyResponse.php(95): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Illegal string ...', '/Users/niclas/S...', 95, Array)
#1 /Users/niclas/Sites/Transport/vendor/lsv/rejseplan-php-api/src/Services/Journey.php(119): RejseplanApi\Services\Response\JourneyResponse::createFromArray(Array)
#2 /Users/niclas/Sites/Transport/vendor/lsv/rejseplan-php-api/src/Services/AbstractServiceCall.php(53): RejseplanApi\Services\Journey->generateResponse(Object(GuzzleHttp\Psr7\Response))
#3 /Users/niclas/Sites/Transport/vendor/lsv/rejseplan-php-api/src/Services/Journey.php(132): RejseplanApi\Services\AbstractServiceCall->doCall()
```

**Comment by niclashedam** [comment]
Please look at
https://github.com/lsv/rejseplan-php-api/pull/7
