### ISSUE TITLE
ErrorException: Undefined index: name

### ISSUE THREAD

**Issue by niclashedam** [lsv/rejseplan-php-api#6]
I was fetching journey details on a train I got from a departure board on Nørreport St.
Thank you very much for providing this repository :-)

```
[2017-02-09 21:58:19] local.ERROR: ErrorException: Undefined index: name in /Users/niclas/Sites/Transport/vendor/lsv/rejseplan-php-api/src/Services/Response/JourneyResponse.php:90
Stack trace:
#0 /Users/niclas/Sites/Transport/vendor/lsv/rejseplan-php-api/src/Services/Response/JourneyResponse.php(90): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/Users/niclas/S...', 90, Array)
#1 /Users/niclas/Sites/Transport/vendor/lsv/rejseplan-php-api/src/Services/Journey.php(119): RejseplanApi\Services\Response\JourneyResponse::createFromArray(Array)
#2 /Users/niclas/Sites/Transport/vendor/lsv/rejseplan-php-api/src/Services/AbstractServiceCall.php(53): RejseplanApi\Services\Journey->generateResponse(Object(GuzzleHttp\Psr7\Response))
#3 /Users/niclas/Sites/Transport/vendor/lsv/rejseplan-php-api/src/Services/Journey.php(132): RejseplanApi\Services\AbstractServiceCall->doCall()
```

**Comment by niclashedam** [comment]
Please look at
https://github.com/lsv/rejseplan-php-api/pull/7
